baseURL = 'https://yourusername.github.io'
languageCode = 'en-uk'
title = 'Test Automation Station'
theme = "PaperMod"
[build]
    [build.caches]
        [build.caches.images]
            dir = ':cacheDir/images'

[params]
    ShowReadingTime =  true
    ShowShareButtons = true